# Generated by Django 4.2.11 on 2024-11-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=100)),
                ('sqft', models.DecimalField(decimal_places=2, max_digits=25)),
                ('capacity', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.CharField(max_length=500)),
            ],
        ),
    ]
